/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 35
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PERCENT = 1,
  sym_variable_name = 2,
  anon_sym_DOLLARnoop_LPAREN = 3,
  anon_sym_DOLLAR = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  sym_function_name = 7,
  anon_sym_COMMA = 8,
  sym_escape_sequence = 9,
  sym_text = 10,
  sym_argument_text = 11,
  sym__noop_content = 12,
  sym_source_file = 13,
  sym__expression = 14,
  sym_variable = 15,
  sym_noop = 16,
  sym_function_call = 17,
  sym__argument_list = 18,
  sym_argument = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym__argument_list_repeat1 = 21,
  aux_sym_argument_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PERCENT] = "%",
  [sym_variable_name] = "variable_name",
  [anon_sym_DOLLARnoop_LPAREN] = "$noop(",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_function_name] = "function_name",
  [anon_sym_COMMA] = ",",
  [sym_escape_sequence] = "escape_sequence",
  [sym_text] = "text",
  [sym_argument_text] = "argument_text",
  [sym__noop_content] = "_noop_content",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_variable] = "variable",
  [sym_noop] = "noop",
  [sym_function_call] = "function_call",
  [sym__argument_list] = "_argument_list",
  [sym_argument] = "argument",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__argument_list_repeat1] = "_argument_list_repeat1",
  [aux_sym_argument_repeat1] = "argument_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_variable_name] = sym_variable_name,
  [anon_sym_DOLLARnoop_LPAREN] = anon_sym_DOLLARnoop_LPAREN,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_function_name] = sym_function_name,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_text] = sym_text,
  [sym_argument_text] = sym_argument_text,
  [sym__noop_content] = sym__noop_content,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_variable] = sym_variable,
  [sym_noop] = sym_noop,
  [sym_function_call] = sym_function_call,
  [sym__argument_list] = sym__argument_list,
  [sym_argument] = sym_argument,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__argument_list_repeat1] = aux_sym__argument_list_repeat1,
  [aux_sym_argument_repeat1] = aux_sym_argument_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLARnoop_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_text] = {
    .visible = true,
    .named = true,
  },
  [sym__noop_content] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_noop] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__argument_list] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 9,
  [14] = 12,
  [15] = 11,
  [16] = 10,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 25,
  [29] = 24,
  [30] = 30,
  [31] = 26,
  [32] = 23,
  [33] = 27,
  [34] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == 'p') ADVANCE(2);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(25);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(8);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == ':') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '%' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_variable_name);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '%' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_variable_name);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOLLARnoop_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_function_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '%' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_argument_text);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '%' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '\\') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 13},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0, .external_lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0, .external_lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 11},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_variable_name] = ACTIONS(1),
    [anon_sym_DOLLARnoop_LPAREN] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_function_name] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_argument_text] = ACTIONS(1),
    [sym__noop_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym__expression] = STATE(7),
    [sym_variable] = STATE(7),
    [sym_noop] = STATE(7),
    [sym_function_call] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DOLLARnoop_LPAREN] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [sym_escape_sequence] = ACTIONS(11),
    [sym_text] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_variable] = STATE(5),
    [sym_noop] = STATE(5),
    [sym_function_call] = STATE(5),
    [sym__argument_list] = STATE(26),
    [sym_argument] = STATE(17),
    [aux_sym__argument_list_repeat1] = STATE(18),
    [aux_sym_argument_repeat1] = STATE(5),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_DOLLARnoop_LPAREN] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_argument_text] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_variable] = STATE(5),
    [sym_noop] = STATE(5),
    [sym_function_call] = STATE(5),
    [sym__argument_list] = STATE(31),
    [sym_argument] = STATE(17),
    [aux_sym__argument_list_repeat1] = STATE(18),
    [aux_sym_argument_repeat1] = STATE(5),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_DOLLARnoop_LPAREN] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_argument_text] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym_variable] = STATE(5),
    [sym_noop] = STATE(5),
    [sym_function_call] = STATE(5),
    [sym_argument] = STATE(21),
    [aux_sym_argument_repeat1] = STATE(5),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_DOLLARnoop_LPAREN] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [sym_escape_sequence] = ACTIONS(23),
    [sym_argument_text] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(15), 1,
      anon_sym_DOLLARnoop_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DOLLAR,
    ACTIONS(29), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(31), 2,
      sym_escape_sequence,
      sym_argument_text,
    STATE(6), 4,
      sym_variable,
      sym_noop,
      sym_function_call,
      aux_sym_argument_repeat1,
  [24] = 6,
    ACTIONS(33), 1,
      anon_sym_PERCENT,
    ACTIONS(36), 1,
      anon_sym_DOLLARnoop_LPAREN,
    ACTIONS(39), 1,
      anon_sym_DOLLAR,
    ACTIONS(42), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(44), 2,
      sym_escape_sequence,
      sym_argument_text,
    STATE(6), 4,
      sym_variable,
      sym_noop,
      sym_function_call,
      aux_sym_argument_repeat1,
  [48] = 6,
    ACTIONS(5), 1,
      anon_sym_PERCENT,
    ACTIONS(7), 1,
      anon_sym_DOLLARnoop_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 2,
      sym_escape_sequence,
      sym_text,
    STATE(8), 5,
      sym__expression,
      sym_variable,
      sym_noop,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [72] = 6,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(56), 1,
      anon_sym_DOLLARnoop_LPAREN,
    ACTIONS(59), 1,
      anon_sym_DOLLAR,
    ACTIONS(62), 2,
      sym_escape_sequence,
      sym_text,
    STATE(8), 5,
      sym__expression,
      sym_variable,
      sym_noop,
      sym_function_call,
      aux_sym_source_file_repeat1,
  [96] = 2,
    ACTIONS(67), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 6,
      anon_sym_PERCENT,
      anon_sym_DOLLARnoop_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_escape_sequence,
      sym_argument_text,
  [108] = 2,
    ACTIONS(71), 1,
      anon_sym_DOLLAR,
    ACTIONS(69), 6,
      anon_sym_PERCENT,
      anon_sym_DOLLARnoop_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_escape_sequence,
      sym_argument_text,
  [120] = 2,
    ACTIONS(75), 1,
      anon_sym_DOLLAR,
    ACTIONS(73), 6,
      anon_sym_PERCENT,
      anon_sym_DOLLARnoop_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_escape_sequence,
      sym_argument_text,
  [132] = 2,
    ACTIONS(79), 1,
      anon_sym_DOLLAR,
    ACTIONS(77), 6,
      anon_sym_PERCENT,
      anon_sym_DOLLARnoop_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_escape_sequence,
      sym_argument_text,
  [144] = 2,
    ACTIONS(67), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 5,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
      anon_sym_DOLLARnoop_LPAREN,
      sym_escape_sequence,
      sym_text,
  [155] = 2,
    ACTIONS(79), 1,
      anon_sym_DOLLAR,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
      anon_sym_DOLLARnoop_LPAREN,
      sym_escape_sequence,
      sym_text,
  [166] = 2,
    ACTIONS(75), 1,
      anon_sym_DOLLAR,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
      anon_sym_DOLLARnoop_LPAREN,
      sym_escape_sequence,
      sym_text,
  [177] = 2,
    ACTIONS(71), 1,
      anon_sym_DOLLAR,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      anon_sym_PERCENT,
      anon_sym_DOLLARnoop_LPAREN,
      sym_escape_sequence,
      sym_text,
  [188] = 3,
    ACTIONS(21), 1,
      anon_sym_COMMA,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      aux_sym__argument_list_repeat1,
  [198] = 3,
    ACTIONS(21), 1,
      anon_sym_COMMA,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      aux_sym__argument_list_repeat1,
  [208] = 3,
    ACTIONS(21), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      aux_sym__argument_list_repeat1,
  [218] = 3,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    STATE(20), 1,
      aux_sym__argument_list_repeat1,
  [228] = 1,
    ACTIONS(85), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [233] = 1,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
  [237] = 1,
    ACTIONS(92), 1,
      sym_variable_name,
  [241] = 1,
    ACTIONS(94), 1,
      anon_sym_PERCENT,
  [245] = 1,
    ACTIONS(96), 1,
      sym__noop_content,
  [249] = 1,
    ACTIONS(98), 1,
      anon_sym_RPAREN,
  [253] = 1,
    ACTIONS(100), 1,
      anon_sym_LPAREN,
  [257] = 1,
    ACTIONS(102), 1,
      sym__noop_content,
  [261] = 1,
    ACTIONS(104), 1,
      anon_sym_PERCENT,
  [265] = 1,
    ACTIONS(106), 1,
      sym_function_name,
  [269] = 1,
    ACTIONS(108), 1,
      anon_sym_RPAREN,
  [273] = 1,
    ACTIONS(110), 1,
      sym_variable_name,
  [277] = 1,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
  [281] = 1,
    ACTIONS(114), 1,
      sym_function_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 24,
  [SMALL_STATE(7)] = 48,
  [SMALL_STATE(8)] = 72,
  [SMALL_STATE(9)] = 96,
  [SMALL_STATE(10)] = 108,
  [SMALL_STATE(11)] = 120,
  [SMALL_STATE(12)] = 132,
  [SMALL_STATE(13)] = 144,
  [SMALL_STATE(14)] = 155,
  [SMALL_STATE(15)] = 166,
  [SMALL_STATE(16)] = 177,
  [SMALL_STATE(17)] = 188,
  [SMALL_STATE(18)] = 198,
  [SMALL_STATE(19)] = 208,
  [SMALL_STATE(20)] = 218,
  [SMALL_STATE(21)] = 228,
  [SMALL_STATE(22)] = 233,
  [SMALL_STATE(23)] = 237,
  [SMALL_STATE(24)] = 241,
  [SMALL_STATE(25)] = 245,
  [SMALL_STATE(26)] = 249,
  [SMALL_STATE(27)] = 253,
  [SMALL_STATE(28)] = 257,
  [SMALL_STATE(29)] = 261,
  [SMALL_STATE(30)] = 265,
  [SMALL_STATE(31)] = 269,
  [SMALL_STATE(32)] = 273,
  [SMALL_STATE(33)] = 277,
  [SMALL_STATE(34)] = 281,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_noop, 2, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_noop, 2, 0, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 2),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 2),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 2),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [90] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__noop_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__noop_content] = sym__noop_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__noop_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_taggerscript_external_scanner_create(void);
void tree_sitter_taggerscript_external_scanner_destroy(void *);
bool tree_sitter_taggerscript_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_taggerscript_external_scanner_serialize(void *, char *);
void tree_sitter_taggerscript_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_taggerscript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_taggerscript_external_scanner_create,
      tree_sitter_taggerscript_external_scanner_destroy,
      tree_sitter_taggerscript_external_scanner_scan,
      tree_sitter_taggerscript_external_scanner_serialize,
      tree_sitter_taggerscript_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "taggerscript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 234,
      .minor_version = 4,
      .patch_version = 10,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
